# Generated by Django 3.2.16 on 2023-08-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20230829_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='quantity',
        ),
        migrations.CreateModel(
            name='IngridientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('ingridient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='recipe.ingridient')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipe.ingridientamount', verbose_name='Ингридиенты'),
        ),
    ]
