# Generated by Django 3.2.16 on 2023-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20230920_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.IngredientForRecipe', to='recipe.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
