version: '3.3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  nginx:
    build: ./infra/
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ../frontend/build:/usr/share/nginx/html/
    #   - ../docs/:/usr/share/nginx/html/api/docs/
