# Generated by Django 3.2.16 on 2023-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230825_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписчик'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
