# Generated by Django 3.2.16 on 2023-08-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230827_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
