# Generated by Django 3.2.16 on 2023-08-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
